name: CI/CD Build and Deploy to AKS

on:
  push:
    branches: [ main ]

env:
  ACR_NAME: restaurantyacr2024
  ACR_LOGIN_SERVER: restaurantyacr2024.azurecr.io
  RG: restauranty-rg
  CLUSTER: restauranty-aks

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install auth dependencies
        working-directory: ./backend/auth
        run: npm ci

      - name: Install discounts dependencies
        working-directory: ./backend/discounts
        run: npm ci

      - name: Install items dependencies
        working-directory: ./backend/items
        run: npm ci

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: CI='' npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RG }}
          cluster-name: ${{ env.CLUSTER }}

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build & Push Auth Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/restauranty-auth-service:latest ./backend/auth
          docker push ${{ env.ACR_LOGIN_SERVER }}/restauranty-auth-service:latest

      - name: Build & Push Discounts Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/restauranty-discounts-service:latest ./backend/discounts
          docker push ${{ env.ACR_LOGIN_SERVER }}/restauranty-discounts-service:latest

      - name: Build & Push Items Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/restauranty-items-service:latest ./backend/items
          docker push ${{ env.ACR_LOGIN_SERVER }}/restauranty-items-service:latest

      - name: Build & Push Client Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/restauranty-client:latest ./client
          docker push ${{ env.ACR_LOGIN_SERVER }}/restauranty-client:latest

      - name: Deploy to AKS (apply all K8s manifests)
        run: kubectl apply -f k8s/

      - name: Upgrade Grafana Ingress (Helm)
        run: |
          helm upgrade --install grafana-ingress ./grafana-ingress \
            --namespace monitoring \
            --set grafanaHost=grafana.yorgos.site

      - name: Upgrade Prometheus Ingress (Helm)
        run: |
          helm upgrade --install prometheus-ingress ./prometheus-ingress \
            --namespace monitoring \
            --set prometheusHost=prometheus.yorgos.site

      - name: Rollout restart deployments
        run: |
          kubectl rollout restart deployment/auth-deployment -n default
          kubectl rollout restart deployment/discounts-deployment -n default
          kubectl rollout restart deployment/items-deployment -n default
          kubectl rollout restart deployment/client-deployment -n default
